# Dev specific config
spring:
  profiles:
    active: dev

    # Enable detailed SQL logging in dev
    jpa:
      show-sql: true
      properties:
        hibernate:
          format_sql: true
          use_sql_comments: true

    # Dev logging
    logging:
      level:
        org.example: TRACE
        org.springframework.kafka: DEBUG
        org.hibernate.SQL: DEBUG
        org.hibernate.type.descriptor.sql: TRACE