# Main app config
spring:
  application:
    name: spring-kafka-demo

    # DB config
    datasource:
      url: jdbc:h2:mem:testdb
      driver-class-name: org.h2.Driver
      username: sa
      password: password

    # JPA/Hibernate Config
    jpa:
      hibernate:
        ddl-auto: create-drop #creates tables on startup, drops on shutdown
      properties:
        hibernate:
          dialect: org.hibernate.dialect.H2Dialect
          format_sql: true
      show-sql: true

    # H2 Console Config (for dev)
    h2:
      console:
        enanbled: true
        path: /h2-console

    # Kafka Config
    kafka:
      # Bootstrap Servers - Kafka broker addresses
      bootstrap-servers: localhost:9092

      # Producer configuration
      producer:
        key-serializer: org.apache.kafka.common.serialization.StringSerializer
        value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
        properties:
          spring.json.type.mapping: orderEventDTO:org.example.dto.OrderEventDTO

      # Consumer configuration
      consumer:
        group-id: order-processing-group
        auto-offset-reset: earliest
        key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
        value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
        properties:
          spring.json.trusted.packages: "*"
          spring.json.type.mapping: orderEventDTO:org.example.dto.OrderEventDTO

# App-specific config
app:
  kafka:
    topic:
      order-events: order-events-topic

# Logging Config
logging:
  level:
    org.example: DEBUG
    org.springframework.kafka: INFO
    org.apache.kafka: WARN